name: Integration Tests

on:
  push:
    branches: [ main, 'devin/**' ]
  pull_request:
    branches: [ main ]

jobs:
  integration-test:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_DB: ahamo_dummy_demo2_test
          POSTGRES_USER: ahamo_user
          POSTGRES_PASSWORD: ahamo_password
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Cache Gradle packages
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
          
    - name: Wait for PostgreSQL
      run: |
        until pg_isready -h localhost -p 5432 -U ahamo_user; do
          echo "Waiting for PostgreSQL..."
          sleep 2
        done
      env:
        PGPASSWORD: ahamo_password
        
    - name: Run unit tests
      run: ./gradlew test
      
    - name: Run integration tests
      run: ./gradlew integrationTest
      env:
        DB_USERNAME: ahamo_user
        DB_PASSWORD: ahamo_password
        
    - name: Generate test report
      run: ./gradlew jacocoTestReport
      if: always()
      
    - name: Upload test results
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: test-results
        path: |
          build/reports/tests/
          build/reports/jacoco/
